"""Synthetic official-encoder fixtures and mixed mission ownership tests."""

import asyncio
import hashlib
from base64 import b64decode
from collections import Counter
from dataclasses import replace
from itertools import product
from types import SimpleNamespace
from unittest.mock import AsyncMock, Mock
from uuid import UUID

import pytest
from google.protobuf.message import DecodeError

from custom_components.matic_robot.client.api import MaticHermesClient
from custom_components.matic_robot.client.commands import (
    CleaningMode as Mode,
)
from custom_components.matic_robot.client.commands import (
    CoverageSetting as Setting,
)
from custom_components.matic_robot.client.commands import (
    _wrapped_uuid,
    encode_coverage_command,
    encode_mixed_coverage_commands,
)
from custom_components.matic_robot.client.commands import (
    encode_mixed_coverage_commands as build_mixed_coverage_commands,
)
from custom_components.matic_robot.client.coverage_goals import (
    coverage_command_goal_signatures,
    coverage_plan_goal_signatures,
    coverage_readback_matches,
)
from custom_components.matic_robot.client.exceptions import (
    CoverageGuardError,
    CoverageGuardReason,
    MaticError,
)
from custom_components.matic_robot.client.models import FloorPlan, RobotOperationalState
from custom_components.matic_robot.client.wire import (
    bytes_fields,
    uuid_string,
)
from custom_components.matic_robot.client.wire import (
    first_bytes as b,
)
from custom_components.matic_robot.client.wire import (
    first_varint as v,
)
from custom_components.matic_robot.plans import (
    PLAN_SESSION_ID,
    CleaningRoom,
    leg_groups,
)
from tests.wire_builders import _field, _varint_field

# Generated by the official offline native encoder from synthetic mission 42,
# partition/rooms below, and deterministic synthetic round UUIDs. No robot data.
OFFICIAL_VACUUM = b64decode(
    "eqYMCqMMGqAMEgQSAgoAGgUVKgAAACrgCwpcMiIKFhIUEhIJNEI0EnhWNBIRZAB4VjQSNIIaCAgCEAAgACgAOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJEUEREREREREREREREREREYEKXDIiChYSFBISCTRCNBJ4VjQSEWUAeFY0EjSCGggIAhAAIAAoATo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCRFBERERERERERERERERERGBClwyIgoWEhQSEgk0QjQSeFY0EhFmAHhWNBI0ghoICAIQACAAKAI6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkRQRERERERERERERERERERgQpcMiIKFhIUEhIJNEI0EnhWNBIRZwB4VjQSNIIaCAgCEAAgACgDOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJEUEREREREREREREREREREYEKXDIiChYSFBISCTRCNBJ4VjQSEWgAeFY0EjSCGggIAhABIAAoADo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCRFBERERERERERERERERERGBClwyIgoWEhQSEgk0QjQSeFY0EhFpAHhWNBI0ghoICAIQASAAKAE6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkRQRERERERERERERERERERgQpcMiIKFhIUEhIJNEI0EnhWNBIRagB4VjQSNIIaCAgCEAEgACgCOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJEUEREREREREREREREREREYEKXDIiChYSFBISCTRCNBJ4VjQSEWsAeFY0EjSCGggIAhABIAAoAzo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCRFBERERERERERERERERERGBClwyIgoWEhQSEgk0QjQSeFY0EhFsAHhWNBI0ghoICAEQACAAKAA6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkiQiIiIiIiIhEiIiIiIiIiggpcMiIKFhIUEhIJNEI0EnhWNBIRbQB4VjQSNIIaCAgBEAAgACgBOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJIkIiIiIiIiIRIiIiIiIiIoIKXDIiChYSFBISCTRCNBJ4VjQSEW4AeFY0EjSCGggIARAAIAAoAjo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCSJCIiIiIiIiESIiIiIiIiKCClwyIgoWEhQSEgk0QjQSeFY0EhFvAHhWNBI0ghoICAEQACAAKAM6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkiQiIiIiIiIhEiIiIiIiIiggpcMiIKFhIUEhIJNEI0EnhWNBIRcAB4VjQSNIIaCAgBEAEgACgAOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJIkIiIiIiIiIRIiIiIiIiIoIKXDIiChYSFBISCTRCNBJ4VjQSEXEAeFY0EjSCGggIARABIAAoATo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCSJCIiIiIiIiESIiIiIiIiKCClwyIgoWEhQSEgk0QjQSeFY0EhFyAHhWNBI0ghoICAEQASAAKAI6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkiQiIiIiIiIhEiIiIiIiIiggpcMiIKFhIUEhIJNEI0EnhWNBIRcwB4VjQSNIIaCAgBEAEgACgDOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJIkIiIiIiIiIRIiIiIiIiIoIyFhIUEhIJM0MzMzMzMzMRMzMzMzMzM4M6FgoUEhIJMECiCghwLZ8RKP/X9jGAn6w="
)
OFFICIAL_MOP = b64decode(
    "eq4JCqsJGqgJEgQSAgoAGgUVKgAAACroCApcMiIKFhIUEhIJNEI0EnhWNBIRZAB4VjQSNIIaCAgCEAAgACgAOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJEUEREREREREREREREREREYEKXDIiChYSFBISCTRCNBJ4VjQSEWUAeFY0EjSCGggIAhAAIAAoATo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCRFBERERERERERERERERERGBClwyIgoWEhQSEgk0QjQSeFY0EhFmAHhWNBI0ghoICAIQACAAKAI6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkRQRERERERERERERERERERgQpcMiIKFhIUEhIJNEI0EnhWNBIRZwB4VjQSNIIaCAgCEAAgACgDOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJEUEREREREREREREREREREYEKXDIiChYSFBISCTRCNBJ4VjQSEWgAeFY0EjSCGggIAhABIAAoADo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCRFBERERERERERERERERERGBClwyIgoWEhQSEgk0QjQSeFY0EhFpAHhWNBI0ghoICAIQASAAKAE6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkRQRERERERERERERERERERgQpcMiIKFhIUEhIJNEI0EnhWNBIRagB4VjQSNIIaCAgCEAEgACgCOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJEUEREREREREREREREREREYEKXDIiChYSFBISCTRCNBJ4VjQSEWsAeFY0EjSCGggIAhABIAAoAzo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCRFBERERERERERERERERERGBClwyIgoWEhQSEgk0QjQSeFY0EhFsAHhWNBI0ghoICAEQACABKAA6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkiQiIiIiIiIhEiIiIiIiIiggpcMiIKFhIUEhIJNEI0EnhWNBIRbQB4VjQSNIIaCAgBEAAgASgBOjYKFgoUEhIJqkqqqqqqqqoRqqqqqqqqqooSAgoAGhgaFhIUEhIJIkIiIiIiIiIRIiIiIiIiIoIKXDIiChYSFBISCTRCNBJ4VjQSEW4AeFY0EjSCGggIARAAIAEoAjo2ChYKFBISCapKqqqqqqqqEaqqqqqqqqqKEgIKABoYGhYSFBISCSJCIiIiIiIiESIiIiIiIiKCClwyIgoWEhQSEgk0QjQSeFY0EhFvAHhWNBI0ghoICAEQACABKAM6NgoWChQSEgmqSqqqqqqqqhGqqqqqqqqqihICCgAaGBoWEhQSEgkiQiIiIiIiIhEiIiIiIiIigjIWEhQSEgkzQzMzMzMzMxEzMzMzMzMzgzoWChQSEgkbSlGamLEApBHP/2Ln9/d3ng=="
)
PARTITION = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
ROOMS = ["11111111-1111-4111-8111-111111111111", "22222222-2222-4222-8222-222222222222"]


def _settled_operational_state():
    """Return a verified charging snapshot with no native cleaning task."""
    return RobotOperationalState(
        battery_percentage=None,
        state_codes=(107,),
        error_codes=(),
        charging_idle=False,
        charging=True,
        low_charge=False,
        paused=False,
        cleaning=False,
        returning=False,
    )


def _active_operational_state(*, error_codes=()):
    """Return a verified cleaning snapshot for new-session ownership tests."""
    return RobotOperationalState(
        battery_percentage=None,
        state_codes=(119,),
        error_codes=error_codes,
        charging_idle=False,
        charging=False,
        low_charge=False,
        paused=False,
        cleaning=True,
        returning=False,
    )


def coverage(payload):
    return b(b(b(payload, 15), 1), 3)


def coverage_plan_from_command(payload, *, drop_goal_index=None):
    coverage_payload = coverage(payload)
    goals = [
        goal
        for container in bytes_fields(coverage_payload, 5)
        for field_number in (1, 2)
        for goal in bytes_fields(container, field_number)
    ]
    if drop_goal_index is not None:
        goals.pop(drop_goal_index)
    return _field(7, _field(1, b"".join(_field(1, goal) for goal in goals)))


def _deterministic_mixed_commands(**kwargs):
    command_ids = iter(
        [UUID(int=value) for value in range(1, 17)]
        + [UUID("33333333-3333-4333-8333-333333333333"), UUID(int=999), UUID(int=1000)]
    )
    return build_mixed_coverage_commands(
        **kwargs, command_id_factory=lambda: next(command_ids)
    )


def _synthetic_goal(spec=None, *, duplicate_round=False, region_id=ROOMS[0]):
    if spec is None:
        spec = (
            _varint_field(1, 1)
            + _varint_field(2, 0)
            + _varint_field(3, 77)
            + _varint_field(4, 1)
            + _varint_field(5, 0)
        )
    round_key = _field(
        1, _wrapped_uuid("33333333-3333-4333-8333-333333333333")
    ) + _field(3, spec)
    target = (
        _field(1, _field(1, _wrapped_uuid(PARTITION)))
        + _field(2, _field(1, b""))
        + _field(3, _field(3, _field(2, _wrapped_uuid(region_id))))
    )
    encoded = _field(6, round_key) + _field(7, target)
    return encoded + (_field(6, round_key) if duplicate_round else b"")


def _command_for_goals(*goals):
    return _field(
        15,
        _field(1, _field(3, _field(5, b"".join(_field(1, goal) for goal in goals)))),
    )


def _command_for_goal_containers(*containers):
    return _field(
        15,
        _field(
            1, _field(3, b"".join(_field(5, container) for container in containers))
        ),
    )


def _plan_for_goals(*goals):
    return _field(
        7,
        _field(1, b"".join(_field(1, goal) for goal in goals)),
    )


def _plan_for_signatures(signatures):
    return _plan_for_goals(
        *(
            _synthetic_goal(
                spec=(
                    _varint_field(1, setting)
                    + _varint_field(2, floor)
                    + _varint_field(4, mode)
                    + _varint_field(5, behavior)
                ),
                region_id=region,
            )
            for region, setting, floor, mode, behavior in signatures
        )
    )


def _plan_for_groups(*groups):
    return _field(7, b"".join(_field(1, group) for group in groups))


@pytest.mark.parametrize(
    "official,second_mode", [(OFFICIAL_VACUUM, Mode.VACUUM), (OFFICIAL_MOP, Mode.MOP)]
)
def test_mixed_update_matches_official_bytes(official, second_mode):
    c = coverage(official)
    goals = bytes_fields(b(c, 5), 1)
    rounds = [UUID(uuid_string(b(b(g, 6), 1))) for g in goals]
    rounds += [UUID(int=900 + n) for n in range(16 - len(rounds))]
    session = UUID(uuid_string(b(c, 6)))
    ids = iter([*rounds, session, UUID(int=999), UUID(uuid_string(b(c, 7)))])
    commands = encode_mixed_coverage_commands(
        mission_id=42,
        partition_id=PARTITION,
        region_ids=ROOMS,
        settings=[Setting.QUICK, Setting.OPTIMAL],
        modes=[Mode.VACUUM, second_mode],
        command_id_factory=lambda: next(ids),
    )
    assert commands.update == official
    assert commands.session_id == str(session)
    initial = coverage(commands.initial)
    assert b(initial, 6) == b(c, 6)
    assert b(initial, 7) != b(c, 7)
    assert bytes_fields(b(initial, 5), 1)[:8] == goals[:8]


def test_mixed_commands_keep_a_supplied_session_identity():
    session_id = UUID("33333333-3333-4333-8333-333333333333")
    commands = encode_mixed_coverage_commands(
        mission_id=42,
        partition_id=PARTITION,
        region_ids=ROOMS,
        settings=[Setting.QUICK, Setting.OPTIMAL],
        modes=[Mode.VACUUM, Mode.MOP],
        session_id=session_id,
    )

    assert commands.session_id == str(session_id)
    assert uuid_string(b(coverage(commands.initial), 6)) == str(session_id)
    assert uuid_string(b(coverage(commands.update), 6)) == str(session_id)


@pytest.mark.parametrize(
    "mode1,mode2,setting1,setting2", list(product(Mode, Mode, Setting, Setting))
)
def test_all_mode_setting_pairs_preserve_first_room(mode1, mode2, setting1, setting2):
    commands = encode_mixed_coverage_commands(
        mission_id=42,
        partition_id=PARTITION,
        region_ids=ROOMS,
        settings=[setting1, setting2],
        modes=[mode1, mode2],
    )
    initial, update = map(coverage, (commands.initial, commands.update))
    count = {Mode.VACUUM: 8, Mode.MOP: 4, Mode.BOTH: 12}
    before, after = [bytes_fields(b(c, 5), 1) for c in (initial, update)]
    assert len(after) == count[mode1] + count[mode2]
    assert before[: count[mode1]] == after[: count[mode1]]
    assert b(initial, 6) == b(update, 6)
    for goal in after[count[mode1] :]:
        spec = b(b(goal, 6), 3)
        assert (
            v(spec, 1)
            == {Setting.QUICK: 2, Setting.OPTIMAL: 1, Setting.HEAVY_DUTY: 0}[setting2]
        )
        assert v(spec, 4) in (
            {0, 1} if mode2 == Mode.BOTH else {0} if mode2 == Mode.VACUUM else {1}
        )
        if v(spec, 4) == 1:
            assert v(spec, 2) == 0


def test_coverage_plan_readback_matches_full_transmitted_goal_multiset():
    expected = coverage_command_goal_signatures(OFFICIAL_MOP)
    readback = coverage_plan_goal_signatures(coverage_plan_from_command(OFFICIAL_MOP))

    assert len(expected) == 12
    assert Counter(readback) == Counter(expected)


def _normal_coverage_fixture(mode=Mode.VACUUM):
    floor = FloorPlan(42, PARTITION, b"partition", ())
    payload = encode_coverage_command(
        mission_id=42,
        partition_id=PARTITION,
        region_ids=ROOMS[:1],
        cleaning_mode=mode,
        coverage_setting=Setting.QUICK,
    )
    return floor, payload


def _session_identity(session_id: UUID) -> bytes:
    """Return the active-session key wrapper encoded in normal field 6."""
    command = encode_coverage_command(
        mission_id=42,
        partition_id=PARTITION,
        region_ids=ROOMS[:1],
        cleaning_mode=Mode.VACUUM,
        coverage_setting=Setting.QUICK,
        session_id=session_id,
    )
    return b(coverage(command), 6)


@pytest.mark.parametrize("error_codes", [(), (900,)])
async def test_normal_coverage_readback_requires_exact_retained_goals(error_codes):
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID("33333333-3333-4333-8333-333333333333")
    identity = _session_identity(session_id)
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[identity, identity, identity]
    )
    client.async_get_state = AsyncMock(
        return_value=_active_operational_state(error_codes=error_codes)
    )
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )
    client.async_get_floor_plan = AsyncMock(return_value=floor)

    await client._async_wait_for_coverage_readback(
        Counter(coverage_command_goal_signatures(payload)),
        floor,
        pre_dispatch_identity=b"prior-session",
        expected_session_id=str(session_id),
    )

    assert client.async_get_cleaning_session_identity.await_count == 3
    assert client.async_get_state.await_count == 3
    client.async_get_floor_plan.assert_awaited_once()


@pytest.mark.parametrize("mode", (Mode.MOP, Mode.BOTH))
async def test_normal_start_accepts_only_the_observed_mop_goal_omission(
    mode, monkeypatch
):
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture(mode)
    session_id = UUID("33333333-3333-4333-8333-333333333333")
    identity = _session_identity(session_id)
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.uuid4", lambda: session_id
    )
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", identity, identity, identity]
    )
    client.async_get_state = AsyncMock(
        side_effect=[
            _settled_operational_state(),
            _active_operational_state(),
            _active_operational_state(),
            _active_operational_state(),
        ]
    )
    client._async_send_user_payload = AsyncMock()
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload, drop_goal_index=-1)
    )
    client.async_get_floor_plan = AsyncMock(return_value=floor)

    await client.async_start_coverage(
        floor,
        ROOMS[:1],
        cleaning_mode=mode,
        coverage_setting=Setting.QUICK,
        require_settings_readback=True,
    )

    client._async_send_user_payload.assert_awaited_once()
    assert uuid_string(
        b(coverage(client._async_send_user_payload.await_args.args[0]), 6)
    ) == str(session_id)
    client.async_get_floor_plan.assert_awaited_once()


@pytest.mark.parametrize(
    "mode,corruption",
    (
        (Mode.MOP, "missing_mop_sibling"),
        (Mode.BOTH, "missing_vacuum_goal"),
        (Mode.MOP, "changed_setting"),
        (Mode.MOP, "extra_goal"),
    ),
)
async def test_normal_start_fails_closed_on_other_readback_changes(
    mode, corruption, monkeypatch
):
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture(mode)
    expected = list(coverage_command_goal_signatures(payload))
    actual = expected.copy()
    if corruption == "missing_mop_sibling":
        actual.remove(next(goal for goal in actual if goal[2:] == (0, 1, 0)))
    elif corruption == "missing_vacuum_goal":
        actual.remove(next(goal for goal in actual if goal[2:4] == (0, 0)))
    elif corruption == "changed_setting":
        index = next(i for i, goal in enumerate(actual) if goal[3:] == (1, 2))
        goal = actual[index]
        actual[index] = (goal[0], goal[1] + 1, *goal[2:])
    else:
        actual.append(actual[0])

    session_id = UUID("33333333-3333-4333-8333-333333333333")
    identity = _session_identity(session_id)
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.uuid4", lambda: session_id
    )
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", identity, identity]
    )
    client.async_get_state = AsyncMock(
        side_effect=[_settled_operational_state(), _active_operational_state()]
    )
    client._async_send_user_payload = AsyncMock()
    client.async_get_property = AsyncMock(return_value=_plan_for_signatures(actual))
    client.async_get_floor_plan = AsyncMock()
    clock = iter((0.0, 100.0))
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", lambda: next(clock)
    )

    with pytest.raises(MaticError, match="did not report requested settings"):
        await client.async_start_coverage(
            floor,
            ROOMS[:1],
            cleaning_mode=mode,
            coverage_setting=Setting.QUICK,
            require_settings_readback=True,
        )

    client._async_send_user_payload.assert_awaited_once()
    client.async_get_floor_plan.assert_not_awaited()


async def test_normal_coverage_readback_rejects_unavailable_task_identity():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    client.async_get_cleaning_session_identity = AsyncMock(return_value=None)

    with pytest.raises(MaticError, match="identity became unavailable"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(UUID(int=100)),
        )


async def test_normal_coverage_readback_rejects_a_replaced_task(monkeypatch):
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[
            _session_identity(session_id),
            _session_identity(UUID(int=101)),
        ]
    )
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=True)
    client.async_get_property = AsyncMock(return_value=b"malformed")
    clock = iter((0.0, 0.0))
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", lambda: next(clock)
    )
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.asyncio.sleep", AsyncMock()
    )

    with pytest.raises(MaticError, match="does not match dispatched coverage"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )


async def test_normal_coverage_readback_rejects_unparseable_identity():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    client.async_get_cleaning_session_identity = AsyncMock(return_value=b"\xff")
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )

    with pytest.raises(MaticError, match="cannot be correlated to coverage"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(UUID(int=100)),
        )

    client.async_get_property.assert_not_awaited()


async def test_normal_coverage_readback_rejects_identity_wrapper_replacement(
    monkeypatch,
):
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    identity = _session_identity(session_id)
    changed_encoding = identity + _varint_field(99, 1)
    assert uuid_string(identity) == uuid_string(changed_encoding) == str(session_id)
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[identity, changed_encoding]
    )
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=True)
    client.async_get_property = AsyncMock(return_value=b"malformed")
    clock = iter((0.0, 0.0))
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", lambda: next(clock)
    )
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.asyncio.sleep", AsyncMock()
    )

    with pytest.raises(MaticError, match="mission changed during coverage readback"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )


async def test_normal_coverage_readback_rejects_changed_identity_after_match():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[_session_identity(session_id), _session_identity(UUID(int=101))]
    )
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=True)
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )

    with pytest.raises(MaticError, match="mission changed during coverage readback"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )


async def test_normal_coverage_readback_rejects_inactive_new_session_after_match():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    identity = _session_identity(session_id)
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[identity, identity]
    )
    client.async_get_active_cleaning_session_state = AsyncMock(
        side_effect=[True, False]
    )
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )

    with pytest.raises(MaticError, match="became inactive during coverage readback"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )


async def test_normal_coverage_readback_rejects_changed_floor():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    identity = _session_identity(session_id)
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[identity, identity]
    )
    client.async_get_active_cleaning_session_state = AsyncMock(side_effect=[True, True])
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )
    client.async_get_floor_plan = AsyncMock(
        return_value=FloorPlan(43, PARTITION, b"partition", ())
    )

    with pytest.raises(MaticError, match="Room map changed"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )


async def test_normal_coverage_readback_rejects_identity_change_during_floor_read():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    identity = _session_identity(session_id)
    client.async_get_cleaning_session_identity = AsyncMock(return_value=identity)
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=True)

    async def replace_identity_during_floor_read():
        client.async_get_cleaning_session_identity.return_value = _session_identity(
            UUID(int=101)
        )
        return floor

    client.async_get_floor_plan = AsyncMock(
        side_effect=replace_identity_during_floor_read
    )
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )

    with pytest.raises(MaticError, match="mission changed during coverage readback"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )


async def test_normal_coverage_readback_rejects_inactive_task_after_floor_read():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    identity = _session_identity(session_id)
    client.async_get_cleaning_session_identity = AsyncMock(return_value=identity)
    active_reader = AsyncMock(return_value=True)
    client.async_get_active_cleaning_session_state = active_reader

    async def finish_floor_read_after_task_ends():
        active_reader.return_value = False
        return floor

    client.async_get_floor_plan = AsyncMock(
        side_effect=finish_floor_read_after_task_ends
    )
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )

    with pytest.raises(MaticError, match="became inactive during coverage readback"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )

    assert client.async_get_cleaning_session_identity.await_count == 2


async def test_normal_coverage_readback_mismatch_times_out(monkeypatch):
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    session_id = UUID(int=100)
    client.async_get_cleaning_session_identity = AsyncMock(
        return_value=b"prior-session"
    )
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=True)
    client.async_get_property = AsyncMock(return_value=b"malformed")
    clock = iter((0.0, 9.0))
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", lambda: next(clock)
    )

    with pytest.raises(MaticError, match="did not report requested settings"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(session_id),
        )


async def test_normal_readback_cannot_accept_retained_plan_for_prior_identity(
    monkeypatch,
):
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    prior_identity = b"completed-native-session"
    client.async_get_cleaning_session_identity = AsyncMock(return_value=prior_identity)
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=False)
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )
    clock = iter((0.0, 9.0))
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", lambda: next(clock)
    )

    with pytest.raises(MaticError, match="did not report requested settings"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=prior_identity,
            expected_session_id=str(UUID(int=100)),
        )

    client.async_get_property.assert_not_awaited()
    client.async_get_active_cleaning_session_state.assert_not_awaited()


async def test_normal_readback_rejects_foreign_identity_before_stale_plan_match():
    client = MaticHermesClient("robot.invalid", 16320)
    floor, payload = _normal_coverage_fixture()
    expected_session_id = UUID(int=100)
    foreign_identity = _session_identity(UUID(int=101))
    client.async_get_cleaning_session_identity = AsyncMock(
        return_value=foreign_identity
    )
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=True)
    client.async_get_property = AsyncMock(
        return_value=coverage_plan_from_command(payload)
    )

    with pytest.raises(MaticError, match="does not match dispatched coverage"):
        await client._async_wait_for_coverage_readback(
            Counter(coverage_command_goal_signatures(payload)),
            floor,
            pre_dispatch_identity=b"prior-session",
            expected_session_id=str(expected_session_id),
        )

    client.async_get_property.assert_not_awaited()
    client.async_get_active_cleaning_session_state.assert_not_awaited()


def test_coverage_plan_readback_preserves_missing_goal_as_mismatch():
    expected = coverage_command_goal_signatures(OFFICIAL_MOP)
    readback = coverage_plan_goal_signatures(
        coverage_plan_from_command(OFFICIAL_MOP, drop_goal_index=-1)
    )

    assert len(readback) == 11
    assert Counter(readback) != Counter(expected)
    assert coverage_readback_matches(Counter(expected), Counter(readback))


def test_mixed_readback_normalization_rejects_other_missing_or_changed_goals():
    expected = Counter(coverage_command_goal_signatures(OFFICIAL_MOP))
    assert not coverage_readback_matches(Counter(), Counter())
    for index in (0, -2):
        actual = Counter(
            coverage_plan_goal_signatures(
                coverage_plan_from_command(OFFICIAL_MOP, drop_goal_index=index)
            )
        )
        assert not coverage_readback_matches(expected, actual)

    normalized = Counter(
        coverage_plan_goal_signatures(
            coverage_plan_from_command(OFFICIAL_MOP, drop_goal_index=-1)
        )
    )
    optional = next(goal for goal in expected if goal[3:] == (1, 3))
    required = next(goal for goal in expected if goal[3:] == (1, 2))
    assert coverage_readback_matches(expected, normalized)
    assert not coverage_readback_matches(expected, normalized + Counter({required: 1}))
    assert not coverage_readback_matches(expected, normalized + Counter({optional: 2}))
    changed_setting = (*required[:1], 2, *required[2:])
    assert not coverage_readback_matches(
        expected, normalized - Counter({required: 1}) + Counter({changed_setting: 1})
    )


def test_mixed_readback_normalization_rejects_unupdated_initial_plan():
    commands = encode_mixed_coverage_commands(
        mission_id=42,
        partition_id=PARTITION,
        region_ids=ROOMS,
        settings=[Setting.QUICK, Setting.OPTIMAL],
        modes=[Mode.VACUUM, Mode.MOP],
    )
    expected = Counter(coverage_command_goal_signatures(commands.update))
    initial = Counter(
        coverage_plan_goal_signatures(coverage_plan_from_command(commands.initial))
    )
    assert not coverage_readback_matches(expected, initial)


def test_mixed_readback_normalizes_each_mop_room_independently():
    commands = encode_mixed_coverage_commands(
        mission_id=42,
        partition_id=PARTITION,
        region_ids=ROOMS,
        settings=[Setting.QUICK, Setting.OPTIMAL],
        modes=[Mode.MOP, Mode.MOP],
    )
    expected = Counter(coverage_command_goal_signatures(commands.update))
    optional = Counter({goal: 1 for goal in expected if goal[3:] == (1, 3)})
    assert optional.total() == 2
    assert coverage_readback_matches(expected, expected - optional)


def test_coverage_plan_readback_ignores_unknown_spec_extensions():
    assert len(coverage_plan_goal_signatures(_plan_for_goals(_synthetic_goal()))) == 1


def test_coverage_goal_decoders_reject_unbounded_or_empty_shapes():
    with pytest.raises(DecodeError, match="byte limit"):
        coverage_command_goal_signatures(b"x" * (2 * 1024 * 1024 + 1))
    with pytest.raises(DecodeError, match="invalid goal count"):
        coverage_command_goal_signatures(_command_for_goals())
    with pytest.raises(DecodeError, match="byte limit"):
        coverage_plan_goal_signatures(b"x" * (2 * 1024 * 1024 + 1))
    with pytest.raises(DecodeError, match="no observed"):
        coverage_plan_goal_signatures(b"")
    with pytest.raises(DecodeError, match="container is malformed"):
        coverage_plan_goal_signatures(_field(7, b""))
    with pytest.raises(DecodeError, match="list is empty"):
        coverage_plan_goal_signatures(_field(7, _field(1, b"")))


def test_coverage_goal_decoders_reject_excessive_counts_and_fields():
    goal = _synthetic_goal()
    all_goal_fields = [_field(1, goal) for _ in range(4097)]
    with pytest.raises(DecodeError, match="invalid goal count"):
        coverage_command_goal_signatures(
            _command_for_goal_containers(
                b"".join(all_goal_fields[:2049]),
                b"".join(all_goal_fields[2049:]),
            )
        )
    with pytest.raises(DecodeError, match="too many active goals"):
        coverage_plan_goal_signatures(
            _plan_for_groups(
                b"".join(all_goal_fields[:2049]),
                b"".join(all_goal_fields[2049:]),
            )
        )
    too_many_fields = _field(7, _field(1, _varint_field(2, 0) * 4097))
    with pytest.raises(DecodeError, match="too many fields"):
        coverage_plan_goal_signatures(too_many_fields)


@pytest.mark.parametrize(
    "goal",
    [
        b"bad",
        _synthetic_goal(
            spec=_field(1, b"\x01")
            + _varint_field(2, 0)
            + _varint_field(4, 1)
            + _varint_field(5, 0)
        ),
        _synthetic_goal(
            spec=_varint_field(1, 1)
            + _varint_field(1, 1)
            + _varint_field(2, 0)
            + _varint_field(4, 1)
            + _varint_field(5, 0)
        ),
        _synthetic_goal(
            spec=_varint_field(1, 1) + _varint_field(2, 0) + _varint_field(4, 1)
        ),
        _synthetic_goal(duplicate_round=True),
    ],
)
def test_coverage_goal_decoder_rejects_malformed_goal_specs(goal):
    with pytest.raises(DecodeError):
        coverage_plan_goal_signatures(_plan_for_goals(goal))


@pytest.mark.parametrize(
    "overrides",
    [
        {"region_ids": ROOMS[:1]},
        {"settings": []},
        {"modes": []},
        {"region_ids": [ROOMS[0], ROOMS[0]]},
        {"modes": ["unknown", Mode.VACUUM]},
        {"settings": ["unknown", Setting.QUICK]},
    ],
)
def test_mixed_rejects_invalid_inputs(overrides):
    args = {
        "mission_id": 42,
        "partition_id": PARTITION,
        "region_ids": ROOMS,
        "settings": [Setting.QUICK, Setting.OPTIMAL],
        "modes": [Mode.VACUUM, Mode.MOP],
    }
    args.update(overrides)
    with pytest.raises(ValueError):
        encode_mixed_coverage_commands(**args)


def test_mixed_groups_keep_legacy_recovery_boundaries():
    rooms = [
        CleaningRoom("one", "One", "vacuum", "quick"),
        CleaningRoom("two", "Two", "mop", "standard"),
        CleaningRoom("three", "Three", "vacuum_and_mop", "heavy_duty"),
    ]
    assert leg_groups(rooms, mixed_settings=True) == [rooms]
    assert leg_groups(rooms, mixed_settings=False) == [[r] for r in rooms]


@pytest.fixture
def mixed_client(monkeypatch):
    client = MaticHermesClient("robot.invalid", 16320)
    session = "33333333-3333-4333-8333-333333333333"
    identity = _wrapped_uuid(session)
    floor = FloorPlan(42, PARTITION, b"partition", ())
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.encode_mixed_coverage_commands",
        _deterministic_mixed_commands,
    )
    client._async_send_user_payload = AsyncMock()

    async def read_back_sent_update(_name):
        update = next(
            call.args[0]
            for call in reversed(client._async_send_user_payload.await_args_list)
            if call.kwargs["command_name"] == "UPDATE_COVERAGE"
        )
        return coverage_plan_from_command(update)

    client.async_get_property = AsyncMock(side_effect=read_back_sent_update)
    identity_reads = 0

    async def current_identity():
        nonlocal identity_reads
        identity_reads += 1
        return b"" if identity_reads <= 2 else identity

    client.async_get_cleaning_session_identity = AsyncMock(side_effect=current_identity)
    client.async_get_state = AsyncMock(
        return_value=replace(_active_operational_state(), current_area="the First")
    )
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=False)
    client.async_get_floor_plan = AsyncMock(return_value=floor)
    client.async_send_user_command = AsyncMock()
    return (
        client,
        identity,
        {
            "floor_plan": floor,
            "region_ids": ROOMS,
            "settings": [Setting.QUICK, Setting.OPTIMAL],
            "modes": [Mode.VACUUM, Mode.MOP],
            "first_room_name": "First",
            "require_current": Mock(),
            "require_owned": Mock(),
            "prepare_stop": AsyncMock(),
            "rollback_stop": AsyncMock(),
            "checkpoint_initial_session": AsyncMock(),
        },
    )


async def test_owned_update_sent_once(mixed_client):
    client, _, args = mixed_client
    order = []

    async def checkpoint(identity_hash):
        order.append("checkpoint")

    async def send(_payload, *, command_name):
        order.append(command_name)

    args["checkpoint_initial_session"] = AsyncMock(side_effect=checkpoint)
    client._async_send_user_payload.side_effect = send
    await client.async_start_mixed_coverage(**args)
    assert order == ["checkpoint", "START_COVERAGE", "UPDATE_COVERAGE"]
    assert [
        c.kwargs["command_name"]
        for c in client._async_send_user_payload.await_args_list
    ] == ["START_COVERAGE", "UPDATE_COVERAGE"]
    args["checkpoint_initial_session"].assert_awaited_once_with(
        hashlib.sha256(
            "33333333-3333-4333-8333-333333333333".encode("ascii")
        ).hexdigest()
    )
    client.async_send_user_command.assert_not_awaited()


async def test_mixed_dispatch_accepts_retained_identity_when_native_task_is_idle(
    mixed_client,
):
    client, identity, args = mixed_client
    baseline = b"completed-session"
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[baseline, baseline, identity, identity, identity, identity]
    )
    client._async_wait_for_mixed_coverage_readback = AsyncMock()

    await client.async_start_mixed_coverage(**args)

    assert [
        call.kwargs["command_name"]
        for call in client._async_send_user_payload.await_args_list
    ] == ["START_COVERAGE", "UPDATE_COVERAGE"]
    assert client.async_get_active_cleaning_session_state.await_count == 1
    client._async_wait_for_mixed_coverage_readback.assert_awaited_once()


@pytest.mark.parametrize("error_codes", [(326,), (900,), (326, 900)])
async def test_mixed_dispatch_preserves_faulted_task_ownership(
    mixed_client, error_codes
):
    client, _, args = mixed_client
    client.async_get_active_cleaning_session_state = (
        MaticHermesClient.async_get_active_cleaning_session_state.__get__(client)
    )
    client.async_get_cleaning_session_identity = AsyncMock(
        return_value=b"retained-native-session"
    )
    client.async_get_state = AsyncMock(
        return_value=replace(_settled_operational_state(), error_codes=error_codes)
    )

    with pytest.raises(CoverageGuardError) as caught:
        await client.async_start_mixed_coverage(**args)

    assert caught.value.reason is CoverageGuardReason.ACTIVITY_UNAVAILABLE
    client._async_send_user_payload.assert_not_awaited()
    client.async_send_user_command.assert_not_awaited()
    args["checkpoint_initial_session"].assert_not_awaited()
    args["prepare_stop"].assert_not_awaited()
    args["rollback_stop"].assert_not_awaited()


async def test_mixed_dispatch_allows_warning_after_native_identity_clears(mixed_client):
    client, identity, args = mixed_client
    client.async_get_active_cleaning_session_state = (
        MaticHermesClient.async_get_active_cleaning_session_state.__get__(client)
    )
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", b"", identity, identity, identity, identity]
    )
    settled = replace(_settled_operational_state(), error_codes=(326,))
    active = replace(
        _active_operational_state(error_codes=(326,)), current_area="First"
    )
    client.async_get_state = AsyncMock(side_effect=[settled, settled, active, active])
    client._async_wait_for_mixed_coverage_readback = AsyncMock()

    await client.async_start_mixed_coverage(**args)

    assert [
        call.kwargs["command_name"]
        for call in client._async_send_user_payload.await_args_list
    ] == ["START_COVERAGE", "UPDATE_COVERAGE"]
    client._async_wait_for_mixed_coverage_readback.assert_awaited_once()
    client.async_send_user_command.assert_not_awaited()


@pytest.mark.parametrize(
    "failure", ["unknown_identity", "unknown_activity", "changed_identity"]
)
async def test_mixed_dispatch_rejects_unverified_preflight(mixed_client, failure):
    client, _, args = mixed_client
    if failure == "unknown_identity":
        client.async_get_cleaning_session_identity = AsyncMock(return_value=None)
        reason = CoverageGuardReason.IDENTITY_UNAVAILABLE
    elif failure == "unknown_activity":
        client.async_get_active_cleaning_session_state = AsyncMock(return_value=None)
        reason = CoverageGuardReason.ACTIVITY_UNAVAILABLE
    else:
        client.async_get_cleaning_session_identity = AsyncMock(
            side_effect=[b"", b"replacement-session"]
        )
        reason = CoverageGuardReason.IDENTITY_CHANGED

    with pytest.raises(CoverageGuardError) as caught:
        await client.async_start_mixed_coverage(**args)

    assert caught.value.reason is reason
    client._async_send_user_payload.assert_not_awaited()


async def test_mixed_dispatch_rejects_cleaning_under_retained_completed_identity(
    mixed_client,
):
    client, _, args = mixed_client
    client.async_get_cleaning_session_identity = AsyncMock(
        return_value=b"completed-session"
    )
    client.async_get_state = AsyncMock(
        return_value=replace(_active_operational_state(), current_area="the First")
    )

    with pytest.raises(MaticError, match="mission changed before coverage update"):
        await client.async_start_mixed_coverage(**args)

    assert [
        call.kwargs["command_name"]
        for call in client._async_send_user_payload.await_args_list
    ] == ["START_COVERAGE"]
    client.async_send_user_command.assert_not_awaited()


async def test_explicit_session_id_reaches_both_mixed_writes(mixed_client):
    client, _, args = mixed_client
    # Keep this distinct from _deterministic_mixed_commands' fallback UUID so
    # the test fails if async_start_mixed_coverage drops the explicit value.
    session_id = UUID("77777777-7777-4777-8777-777777777777")
    identity = _wrapped_uuid(str(session_id))
    identity_reads = 0

    async def read_explicit_session_identity():
        nonlocal identity_reads
        identity_reads += 1
        return b"" if identity_reads <= 2 else identity

    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=read_explicit_session_identity
    )
    args["session_id"] = session_id

    await client.async_start_mixed_coverage(**args)

    payloads = [
        call.args[0] for call in client._async_send_user_payload.await_args_list
    ]
    assert [uuid_string(b(coverage(payload), 6)) for payload in payloads] == [
        str(session_id),
        str(session_id),
    ]
    args["checkpoint_initial_session"].assert_awaited_once_with(
        hashlib.sha256(str(session_id).encode("ascii")).hexdigest()
    )


async def test_owned_update_accepts_observed_mop_goal_normalization(mixed_client):
    client, _, args = mixed_client

    async def normalized_readback(_name):
        update = next(
            call.args[0]
            for call in reversed(client._async_send_user_payload.await_args_list)
            if call.kwargs["command_name"] == "UPDATE_COVERAGE"
        )
        return coverage_plan_from_command(update, drop_goal_index=-1)

    client.async_get_property.side_effect = normalized_readback
    await client.async_start_mixed_coverage(**args)

    client.async_get_property.assert_awaited_once_with("coverage_plan")
    client.async_send_user_command.assert_not_awaited()


async def test_mixed_update_readback_mismatch_stops_only_owned_session(
    mixed_client, monkeypatch
):
    client, identity, args = mixed_client
    reads = 0

    async def current_identity():
        nonlocal reads
        reads += 1
        return b"" if reads <= 2 else identity

    async def incomplete_readback(_name):
        update = next(
            call.args[0]
            for call in reversed(client._async_send_user_payload.await_args_list)
            if call.kwargs["command_name"] == "UPDATE_COVERAGE"
        )
        return coverage_plan_from_command(update, drop_goal_index=-2)

    clock = iter((0.0, 9.0))
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", lambda: next(clock)
    )
    client.async_get_cleaning_session_identity = AsyncMock(side_effect=current_identity)
    client.async_get_property.side_effect = incomplete_readback

    with pytest.raises(
        MaticError, match="did not retain all requested mixed coverage goals"
    ):
        await client.async_start_mixed_coverage(**args)

    args["prepare_stop"].assert_awaited_once()
    client.async_send_user_command.assert_awaited_once()


async def test_mixed_update_waits_for_matching_readback(mixed_client, monkeypatch):
    client, identity, args = mixed_client
    reads = 0
    readback_count = 0

    async def current_identity():
        nonlocal reads
        reads += 1
        return b"" if reads <= 2 else identity

    async def changing_readback(_name):
        nonlocal readback_count
        readback_count += 1
        update = next(
            call.args[0]
            for call in reversed(client._async_send_user_payload.await_args_list)
            if call.kwargs["command_name"] == "UPDATE_COVERAGE"
        )
        return coverage_plan_from_command(
            update, drop_goal_index=-2 if readback_count == 1 else None
        )

    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", iter((0.0, 0.0)).__next__
    )
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.asyncio.sleep", AsyncMock()
    )
    client.async_get_cleaning_session_identity = AsyncMock(side_effect=current_identity)
    client.async_get_property.side_effect = changing_readback
    await client.async_start_mixed_coverage(**args)

    assert client.async_get_property.await_count == 2
    client.async_send_user_command.assert_not_awaited()


async def test_mixed_update_malformed_readback_fails_closed(mixed_client, monkeypatch):
    client, identity, args = mixed_client
    reads = 0

    async def current_identity():
        nonlocal reads
        reads += 1
        return b"" if reads <= 2 else identity

    clock = iter((0.0, 9.0))
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", lambda: next(clock)
    )
    client.async_get_cleaning_session_identity = AsyncMock(side_effect=current_identity)
    client.async_get_property.side_effect = None
    client.async_get_property.return_value = b""

    with pytest.raises(
        MaticError, match="did not retain all requested mixed coverage goals"
    ):
        await client.async_start_mixed_coverage(**args)

    client.async_send_user_command.assert_awaited_once()


async def test_mixed_update_readback_request_is_bounded(mixed_client, monkeypatch):
    client, identity, args = mixed_client
    reads = 0
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api._MIXED_COVERAGE_READBACK_TIMEOUT",
        0.001,
    )

    async def current_identity():
        nonlocal reads
        reads += 1
        return b"" if reads <= 2 else identity

    async def stalled_readback(_name):
        await asyncio.Event().wait()

    client.async_get_cleaning_session_identity = AsyncMock(side_effect=current_identity)
    client.async_get_property.side_effect = stalled_readback
    with pytest.raises(TimeoutError):
        await client.async_start_mixed_coverage(**args)

    args["prepare_stop"].assert_awaited_once()
    client.async_send_user_command.assert_awaited_once()


async def test_mixed_update_does_not_stop_replacement_after_stale_readback(
    mixed_client, monkeypatch
):
    client, identity, args = mixed_client
    replacement = _wrapped_uuid("44444444-4444-4444-8444-444444444444")
    identities = iter(
        [b"", b"", identity, identity, identity, identity, replacement, replacement]
    )
    client.async_get_cleaning_session_identity = AsyncMock(side_effect=identities)
    client.async_get_property.side_effect = lambda _name: coverage_plan_from_command(
        next(
            call.args[0]
            for call in reversed(client._async_send_user_payload.await_args_list)
            if call.kwargs["command_name"] == "UPDATE_COVERAGE"
        ),
        drop_goal_index=-2,
    )
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.monotonic", iter((0.0, 0.0)).__next__
    )

    with pytest.raises(MaticError, match="changed during coverage readback"):
        await client.async_start_mixed_coverage(**args)

    args["prepare_stop"].assert_not_awaited()
    client.async_send_user_command.assert_not_awaited()


async def test_mixed_update_does_not_stop_replacement_during_readback(
    mixed_client,
):
    client, identity, args = mixed_client
    replacement = _wrapped_uuid("44444444-4444-4444-8444-444444444444")
    reads = iter(
        [b"", b"", identity, identity, identity, identity, replacement, replacement]
    )
    client.async_get_cleaning_session_identity = AsyncMock(side_effect=reads)

    with pytest.raises(MaticError, match="changed during coverage readback"):
        await client.async_start_mixed_coverage(**args)

    args["prepare_stop"].assert_not_awaited()
    client.async_send_user_command.assert_not_awaited()


async def test_mixed_start_checkpoint_failure_prevents_initial_write(mixed_client):
    client, _, args = mixed_client
    args["checkpoint_initial_session"].side_effect = OSError("storage unavailable")
    with pytest.raises(OSError, match="storage unavailable"):
        await client.async_start_mixed_coverage(**args)
    client._async_send_user_payload.assert_not_awaited()


async def test_mixed_wait_normalizes_room_spacing(mixed_client):
    client, _, args = mixed_client
    args["first_room_name"] = " Living   Room "
    client.async_get_state.return_value = replace(
        _active_operational_state(), current_area="The Living Room"
    )

    await client.async_start_mixed_coverage(**args)

    assert [
        call.kwargs["command_name"]
        for call in client._async_send_user_payload.await_args_list
    ] == ["START_COVERAGE", "UPDATE_COVERAGE"]


async def test_room_transition_before_update_stops_without_updating(mixed_client):
    client, identity, args = mixed_client
    reads = 0

    async def current_identity():
        nonlocal reads
        reads += 1
        return b"" if reads <= 2 else identity

    client.async_get_cleaning_session_identity = AsyncMock(side_effect=current_identity)
    client.async_get_state = AsyncMock(
        side_effect=[
            replace(_active_operational_state(), current_area="First"),
            replace(_active_operational_state(), current_area="Second"),
        ]
    )

    with pytest.raises(MaticError, match="First room changed"):
        await client.async_start_mixed_coverage(**args)

    assert [
        call.kwargs["command_name"]
        for call in client._async_send_user_payload.await_args_list
    ] == ["START_COVERAGE"]
    args["prepare_stop"].assert_awaited_once()
    client.async_send_user_command.assert_awaited_once()


async def test_replaced_mission_during_state_read_is_not_updated_or_stopped(
    mixed_client,
):
    client, identity, args = mixed_client
    replacement = _wrapped_uuid("44444444-4444-4444-8444-444444444444")
    current = {"identity": b""}
    identity_reads = 0

    async def current_identity():
        nonlocal identity_reads
        identity_reads += 1
        return current["identity"]

    async def read_state():
        # The first read is the wait for the generated mission. Replace it on
        # the later pre-update read, after the preceding identity check passed.
        if identity_reads >= 4:
            current["identity"] = replacement
        return replace(_active_operational_state(), current_area="First")

    async def send(payload, *, command_name):
        if command_name == "START_COVERAGE":
            current["identity"] = identity

    client.async_get_cleaning_session_identity = AsyncMock(side_effect=current_identity)
    client.async_get_state = AsyncMock(side_effect=read_state)
    client._async_send_user_payload.side_effect = send

    with pytest.raises(
        MaticError, match="Native mission changed before coverage update"
    ):
        await client.async_start_mixed_coverage(**args)

    assert [
        call.kwargs["command_name"]
        for call in client._async_send_user_payload.await_args_list
    ] == ["START_COVERAGE"]
    args["prepare_stop"].assert_not_awaited()
    client.async_send_user_command.assert_not_awaited()


async def test_replacement_during_stop_fence_persistence_is_not_stopped(mixed_client):
    client, identity, args = mixed_client
    other = _wrapped_uuid("44444444-4444-4444-8444-444444444444")
    client.async_get_floor_plan = AsyncMock(
        return_value=FloorPlan(99, PARTITION, b"changed", ())
    )
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", identity, identity, other]
    )
    with pytest.raises(MaticError, match="Room map changed"):
        await client.async_start_mixed_coverage(**args)
    args["prepare_stop"].assert_awaited_once()
    args["rollback_stop"].assert_awaited_once()
    client.async_send_user_command.assert_not_awaited()


async def test_active_native_mission_rejects_initial_write(mixed_client):
    client, identity, args = mixed_client
    client.async_get_cleaning_session_identity = AsyncMock(return_value=identity)
    client.async_get_active_cleaning_session_state = AsyncMock(return_value=True)
    with pytest.raises(MaticError):
        await client.async_start_mixed_coverage(**args)
    client._async_send_user_payload.assert_not_awaited()


@pytest.mark.parametrize("after_write", [False, True])
async def test_identity_rechecked_around_update(mixed_client, after_write):
    client, identity, args = mixed_client
    other = _wrapped_uuid("44444444-4444-4444-8444-444444444444")
    reads = (
        [b"", b"", identity, identity, identity, other, other]
        if after_write
        else [b"", b"", identity, other, other]
    )
    client.async_get_cleaning_session_identity = AsyncMock(side_effect=reads)
    with pytest.raises(MaticError, match="Native mission changed"):
        await client.async_start_mixed_coverage(**args)
    assert client._async_send_user_payload.await_count == (2 if after_write else 1)
    client.async_send_user_command.assert_not_awaited()


async def test_start_timeout_and_failed_recovery_never_update(
    mixed_client, monkeypatch
):
    client, _, args = mixed_client
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", b"", MaticError("offline")]
    )
    monkeypatch.setattr(
        "custom_components.matic_robot.client.api.asyncio.sleep",
        AsyncMock(side_effect=TimeoutError),
    )
    with pytest.raises(TimeoutError):
        await client.async_start_mixed_coverage(**args)
    assert client._async_send_user_payload.await_count == 1
    client.async_send_user_command.assert_not_awaited()


@pytest.mark.parametrize("rollback_fails", [False, True])
async def test_pre_send_recovery_stop_failure_rolls_back_its_fence(
    mixed_client, rollback_fails
):
    client, identity, args = mixed_client
    client._async_send_user_payload.side_effect = [None, MaticError("update failed")]
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", identity, identity, identity, identity, identity]
    )
    client.async_send_user_command.side_effect = MaticError("STOP rejected")
    if rollback_fails:
        args["rollback_stop"].side_effect = MaticError("storage unavailable")

    with pytest.raises(MaticError, match="update failed"):
        await client.async_start_mixed_coverage(**args)

    client.async_send_user_command.assert_awaited_once()
    args["prepare_stop"].assert_awaited_once()
    args["rollback_stop"].assert_awaited_once()


@pytest.mark.parametrize(
    ("stop_error", "expected_error"),
    [
        (MaticError("STOP response lost"), MaticError),
        (asyncio.CancelledError(), asyncio.CancelledError),
    ],
)
async def test_ambiguous_recovery_stop_keeps_its_fence(
    mixed_client, stop_error, expected_error
):
    client, identity, args = mixed_client
    args["on_recovery_stop_transmitted"] = Mock()
    client._async_send_user_payload.side_effect = [None, MaticError("update failed")]
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", identity, identity, identity, identity, identity]
    )

    async def fail_after_transmission_starts(command, *, on_transmitted=None):
        assert command.name == "STOP"
        assert on_transmitted is not None
        on_transmitted()
        on_transmitted()
        raise stop_error

    client.async_send_user_command.side_effect = fail_after_transmission_starts
    with pytest.raises(expected_error):
        await client.async_start_mixed_coverage(**args)

    args["prepare_stop"].assert_awaited_once()
    args["rollback_stop"].assert_not_awaited()
    args["on_recovery_stop_transmitted"].assert_called_once_with()


async def test_recovery_stop_ack_schedules_settlement_before_dispatch_error(
    mixed_client,
):
    client, identity, args = mixed_client
    args["on_recovery_stop_transmitted"] = Mock()
    client._async_send_user_payload.side_effect = [None, MaticError("update failed")]
    client.async_get_cleaning_session_identity = AsyncMock(
        side_effect=[b"", b"", identity, identity, identity, identity, identity]
    )

    async def stop_acknowledged(command, *, on_transmitted=None):
        assert command.name == "STOP"
        assert on_transmitted is not None
        on_transmitted()

    client.async_send_user_command.side_effect = stop_acknowledged
    with pytest.raises(MaticError, match="update failed"):
        await client.async_start_mixed_coverage(**args)

    args["on_recovery_stop_transmitted"].assert_called_once_with()
    args["rollback_stop"].assert_not_awaited()


@pytest.mark.parametrize("key", ["_region_settings", "_region_modes"])
def test_mismatched_per_room_encoder_options(key):
    from custom_components.matic_robot.client.commands import encode_coverage_command

    with pytest.raises(ValueError, match="per region"):
        encode_coverage_command(
            mission_id=42, partition_id=PARTITION, region_ids=ROOMS, **{key: []}
        )


@pytest.mark.parametrize(
    "failure",
    [
        None,
        "transport",
        "stop",
        "replacement",
        "cancelled",
        "prepare_error",
        "rollback",
        "transmitted_stop",
    ],
)
async def test_entity_mixed_dispatch_guards(hass, failure):
    from homeassistant.exceptions import HomeAssistantError

    from custom_components.matic_robot.plans import (
        PLAN_MOTION_TOKEN,
        CleaningPlanManager,
    )
    from custom_components.matic_robot.vacuum import MaticVacuum
    from tests.test_entities import _entry

    entry = _entry()
    manager = CleaningPlanManager(hass)
    manager._store = SimpleNamespace(async_save=AsyncMock())
    entry.runtime_data.cleaning_plans = manager
    token = manager.begin_managed_motion("synthetic-serial")

    async def send(*args, **kwargs):
        kwargs["require_owned"]()
        if failure == "transport":
            await kwargs["prepare_stop"]()
            raise MaticError("unavailable")
        if failure == "stop":
            assert manager.request_stop("synthetic-serial").behavior == "after_room"
        if failure == "replacement":
            manager.replace_managed_motion("synthetic-serial")
        if failure == "cancelled":
            manager.cancellation_event("synthetic-serial").set()
        if failure == "prepare_error":
            await kwargs["prepare_stop"]()
        if failure == "rollback":
            await kwargs["prepare_stop"]()
            await kwargs["rollback_stop"]()
        if failure == "transmitted_stop":
            await kwargs["prepare_stop"]()
            kwargs["on_recovery_stop_transmitted"]()
            raise MaticError("update failed after recovery STOP")
        kwargs["require_current"]()

    client = entry.runtime_data.coordinator.client
    client.async_start_mixed_coverage = AsyncMock(side_effect=send)
    entity = MaticVacuum(entry)
    entity._schedule_dock_after_stop = Mock()
    params = {
        "rooms": ["Kitchen", "Study"],
        "ordered": True,
        PLAN_MOTION_TOKEN: token,
        PLAN_SESSION_ID: "33333333-3333-4333-8333-333333333333",
        "room_coverage": ["quick", "standard"],
        "room_modes": ["vacuum", "mop"],
    }
    if failure in {"prepare_error", "rollback"}:
        manager.async_mark_stop_pending = AsyncMock(
            side_effect=OSError("synthetic stop-fence persistence failure")
            if failure == "prepare_error"
            else None
        )
        manager.async_clear_stop_pending = AsyncMock()
    if failure in {
        "transport",
        "replacement",
        "cancelled",
        "prepare_error",
        "transmitted_stop",
    }:
        with pytest.raises((HomeAssistantError, MaticError, OSError)):
            await entity.async_send_command("clean_rooms", params)
    else:
        if failure == "stop":
            manager._robot("synthetic-serial")["plans"]["test"] = {
                "finish_current_room": True,
                "finish_current_room_threshold": 50,
            }
            manager._robot("synthetic-serial")["active_plan"] = {
                "plan_id": "test",
                "room_id": "Kitchen",
            }
            await manager.lock("synthetic-serial").acquire()
        try:
            await entity.async_send_command("clean_rooms", params)
        finally:
            if failure == "stop":
                manager.lock("synthetic-serial").release()
    client.async_start_coverage.assert_not_awaited()
    client.async_start_mixed_coverage.assert_awaited_once()
    if failure == "prepare_error":
        manager.async_clear_stop_pending.assert_awaited_once_with(
            "synthetic-serial", run_id=None
        )
    if failure == "rollback":
        manager.async_mark_stop_pending.assert_awaited_once_with(
            "synthetic-serial", run_id=None
        )
        manager.async_clear_stop_pending.assert_awaited_once_with(
            "synthetic-serial", run_id=None
        )
    if failure == "transmitted_stop":
        entity._schedule_dock_after_stop.assert_called_once_with(
            "synthetic-serial", run_id=None
        )


async def test_managed_vacuum_supplies_mixed_session_checkpoint(hass):
    from custom_components.matic_robot.plans import CleaningPlanManager
    from custom_components.matic_robot.vacuum import MaticVacuum
    from tests.test_entities import _entry

    entry = _entry()
    manager = CleaningPlanManager(hass)
    manager._store = SimpleNamespace(async_save=AsyncMock())
    entry.runtime_data.cleaning_plans = manager
    await manager.async_begin_run(
        "synthetic-serial",
        "plan",
        "run",
        2,
        trigger="user",
        service="run_selected_plan",
    )
    await manager.async_set_recovery_checkpoint(
        "synthetic-serial",
        "run",
        {
            "version": 1,
            "phase": "dispatching",
            "mixed_settings": True,
            "leg_index": 0,
        },
    )
    token = manager.begin_managed_motion("synthetic-serial")
    session_id = UUID("33333333-3333-4333-8333-333333333333")
    session_hash = hashlib.sha256(str(session_id).encode("ascii")).hexdigest()

    async def checkpoint(_floor, _rooms, _settings, _modes, **kwargs):
        await kwargs["checkpoint_initial_session"](session_hash)

    client = entry.runtime_data.coordinator.client
    client.async_start_mixed_coverage = AsyncMock(side_effect=checkpoint)
    await MaticVacuum(entry).async_send_command(
        "clean_rooms",
        {
            "rooms": ["Kitchen", "Study"],
            "ordered": True,
            "room_coverage": ["quick", "standard"],
            "room_modes": ["vacuum", "mop"],
            "_matic_plan_run": token,
            PLAN_SESSION_ID: str(session_id),
        },
    )

    client.async_start_mixed_coverage.assert_awaited_once()
    assert (
        client.async_start_mixed_coverage.await_args.kwargs["session_id"] == session_id
    )

    assert (
        manager.recovery_run("synthetic-serial")["recovery_checkpoint"][
            "mixed_initial_session_hash"
        ]
        == session_hash
    )


@pytest.mark.parametrize(
    "extra",
    [
        {"room_coverage": "quick"},
        {"room_modes": ["bad"]},
        {"room_coverage": ["quick", "standard"], "room_modes": ["vacuum", "mop"]},
    ],
)
async def test_entity_rejects_unowned_or_invalid_mixed_parameters(hass, extra):
    from homeassistant.exceptions import ServiceValidationError

    from custom_components.matic_robot.plans import CleaningPlanManager
    from custom_components.matic_robot.vacuum import MaticVacuum
    from tests.test_entities import _entry

    entry = _entry()
    entry.runtime_data.cleaning_plans = CleaningPlanManager(hass)
    with pytest.raises(ServiceValidationError):
        await MaticVacuum(entry).async_send_command(
            "clean_rooms", {"rooms": ["Kitchen", "Study"], **extra}
        )


@pytest.mark.parametrize(
    "mode1,mode2,setting1,setting2", list(product(Mode, Mode, Setting, Setting))
)
async def test_runner_passes_each_rooms_mode_and_setting(
    hass, mode1, mode2, setting1, setting2
):
    from homeassistant.core import ServiceCall

    from custom_components.matic_robot.managed_executor import (
        _async_dispatch_leg_command,
    )

    captured = []

    async def send(call):
        captured.append(call.data)

    hass.services.async_register("vacuum", "send_command", send)
    rooms = [
        CleaningRoom("one", "One", mode1.value, setting1.value),
        CleaningRoom("two", "Two", mode2.value, setting2.value),
    ]
    await _async_dispatch_leg_command(
        hass, ServiceCall(hass, "matic_robot", "run", {}), "vacuum.test", rooms, 1, None
    )
    params = captured[0]["params"]
    assert params["rooms"] == ["one", "two"]
    assert params["ordered"] is True
    assert params["cleaning_mode"] == mode1.value
    assert params["coverage"] == setting1.value
    if (mode1, setting1) == (mode2, setting2):
        assert "room_modes" not in params
        assert "room_coverage" not in params
    else:
        assert params["room_modes"] == [mode1.value, mode2.value]
        assert params["room_coverage"] == [setting1.value, setting2.value]


@pytest.mark.parametrize(
    "failure", ["replacement", "map", "update", "stop", "recovery_unknown"]
)
async def test_failed_update_cannot_replay_or_stop_replacement(mixed_client, failure):
    client, identity, args = mixed_client
    other = _wrapped_uuid("44444444-4444-4444-8444-444444444444")
    if failure == "replacement":
        client.async_get_cleaning_session_identity = AsyncMock(
            side_effect=[b"", b"", other, other]
        )
    elif failure == "map":
        client.async_get_floor_plan = AsyncMock(
            return_value=FloorPlan(99, PARTITION, b"partition", ())
        )
        client.async_get_cleaning_session_identity = AsyncMock(
            side_effect=[b"", b"", identity, identity, identity]
        )
    elif failure in ("update", "recovery_unknown"):
        client._async_send_user_payload.side_effect = [
            None,
            MaticError("update failed"),
        ]
        client.async_get_cleaning_session_identity = AsyncMock(
            side_effect=[
                b"",
                b"",
                identity,
                identity,
                identity,
                identity if failure == "update" else None,
                identity,
            ]
        )
    else:
        args["require_current"].side_effect = [
            None,
            None,
            None,
            MaticError("stop"),
        ]
        client.async_get_cleaning_session_identity = AsyncMock(
            side_effect=[b"", b"", identity, identity]
        )
    with pytest.raises(MaticError):
        await client.async_start_mixed_coverage(**args)
    assert client._async_send_user_payload.await_count <= 2
    assert client.async_send_user_command.await_count == (
        0 if failure in ("replacement", "recovery_unknown") else 1
    )
