# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: hermes_auth.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.client
import grpclib.const

if typing.TYPE_CHECKING:
    import grpclib.server

from . import hermes_auth_pb2


class HermesAuthBase(abc.ABC):
    @abc.abstractmethod
    async def AuthToken(
        self,
        stream: "grpclib.server.Stream[hermes_auth_pb2.TokenRequest, hermes_auth_pb2.BotToken]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/hermes_auth.HermesAuth/AuthToken": grpclib.const.Handler(
                self.AuthToken,
                grpclib.const.Cardinality.UNARY_UNARY,
                hermes_auth_pb2.TokenRequest,
                hermes_auth_pb2.BotToken,
            ),
        }


class HermesAuthStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.AuthToken = grpclib.client.UnaryUnaryMethod(
            channel,
            "/hermes_auth.HermesAuth/AuthToken",
            hermes_auth_pb2.TokenRequest,
            hermes_auth_pb2.BotToken,
        )
