# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: hermes_auth.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11hermes_auth.proto\x12\x0bhermes_auth"\x1f\n\x0cTokenRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t".\n\x08\x42otToken\x12\x0c\n\x04user\x18\x01 \x01(\x0c\x12\x14\n\x0chashed_token\x18\x02 \x01(\x0c\x32K\n\nHermesAuth\x12=\n\tAuthToken\x12\x19.hermes_auth.TokenRequest\x1a\x15.hermes_auth.BotTokenb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hermes_auth_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
