# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: hermes_bot_info.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client

if typing.TYPE_CHECKING:
    import grpclib.server

from . import hermes_bot_info_pb2


class HermesDiscoveryRPCBase(abc.ABC):
    @abc.abstractmethod
    async def GetBotInfo(
        self,
        stream: "grpclib.server.Stream[hermes_bot_info_pb2.Unit, hermes_bot_info_pb2.BotInformation]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def RequestRemoteToken(
        self,
        stream: "grpclib.server.Stream[hermes_bot_info_pb2.RemoteAccessRequest, hermes_bot_info_pb2.RemoteAccessToken]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/hermes_bot_info.HermesDiscoveryRPC/GetBotInfo": grpclib.const.Handler(
                self.GetBotInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                hermes_bot_info_pb2.Unit,
                hermes_bot_info_pb2.BotInformation,
            ),
            "/hermes_bot_info.HermesDiscoveryRPC/RequestRemoteToken": grpclib.const.Handler(
                self.RequestRemoteToken,
                grpclib.const.Cardinality.STREAM_UNARY,
                hermes_bot_info_pb2.RemoteAccessRequest,
                hermes_bot_info_pb2.RemoteAccessToken,
            ),
        }


class HermesDiscoveryRPCStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetBotInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            "/hermes_bot_info.HermesDiscoveryRPC/GetBotInfo",
            hermes_bot_info_pb2.Unit,
            hermes_bot_info_pb2.BotInformation,
        )
        self.RequestRemoteToken = grpclib.client.StreamUnaryMethod(
            channel,
            "/hermes_bot_info.HermesDiscoveryRPC/RequestRemoteToken",
            hermes_bot_info_pb2.RemoteAccessRequest,
            hermes_bot_info_pb2.RemoteAccessToken,
        )
