# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hermes_bot_info.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15hermes_bot_info.proto\x12\x0fhermes_bot_info"\x06\n\x04Unit"\xda\x01\n\x0e\x42otInformation\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\r\x12\x13\n\x0bip4_address\x18\x05 \x01(\t\x12\x13\n\x0bip6_address\x18\x06 \x01(\t\x12\x11\n\tencrypted\x18\x07 \x01(\x08\x12\x15\n\rrequires_auth\x18\x08 \x01(\x08\x12\x14\n\x0cnetwork_auth\x18\t \x01(\x08\x12\x19\n\x11hardware_revision\x18\n \x01(\t"&\n\x13RemoteAccessRequest\x12\x0f\n\x07request\x18\x01 \x01(\t"C\n\x11RemoteAccessToken\x12\x12\n\nbot_serial\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t2\xbc\x01\n\x12HermesDiscoveryRPC\x12\x44\n\nGetBotInfo\x12\x15.hermes_bot_info.Unit\x1a\x1f.hermes_bot_info.BotInformation\x12`\n\x12RequestRemoteToken\x12$.hermes_bot_info.RemoteAccessRequest\x1a".hermes_bot_info.RemoteAccessToken(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hermes_bot_info_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_UNIT"]._serialized_start = 42
    _globals["_UNIT"]._serialized_end = 48
    _globals["_BOTINFORMATION"]._serialized_start = 51
    _globals["_BOTINFORMATION"]._serialized_end = 269
    _globals["_REMOTEACCESSREQUEST"]._serialized_start = 271
    _globals["_REMOTEACCESSREQUEST"]._serialized_end = 309
    _globals["_REMOTEACCESSTOKEN"]._serialized_start = 311
    _globals["_REMOTEACCESSTOKEN"]._serialized_end = 378
    _globals["_HERMESDISCOVERYRPC"]._serialized_start = 381
    _globals["_HERMESDISCOVERYRPC"]._serialized_end = 569
# @@protoc_insertion_point(module_scope)
