# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: hermes.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client

if typing.TYPE_CHECKING:
    import grpclib.server

from . import hermes_pb2


class HermesBase(abc.ABC):
    @abc.abstractmethod
    async def Handshake(
        self, stream: "grpclib.server.Stream[hermes_pb2.Unit, hermes_pb2.Unit]"
    ) -> None:
        pass

    @abc.abstractmethod
    async def FetchCollection(
        self,
        stream: "grpclib.server.Stream[hermes_pb2.CollectionRequest, hermes_pb2.CollectionResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def SendToChannel(
        self,
        stream: "grpclib.server.Stream[hermes_pb2.ChannelRequest, hermes_pb2.ChannelResponse]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/hermes.Hermes/Handshake": grpclib.const.Handler(
                self.Handshake,
                grpclib.const.Cardinality.UNARY_UNARY,
                hermes_pb2.Unit,
                hermes_pb2.Unit,
            ),
            "/hermes.Hermes/FetchCollection": grpclib.const.Handler(
                self.FetchCollection,
                grpclib.const.Cardinality.STREAM_STREAM,
                hermes_pb2.CollectionRequest,
                hermes_pb2.CollectionResponse,
            ),
            "/hermes.Hermes/SendToChannel": grpclib.const.Handler(
                self.SendToChannel,
                grpclib.const.Cardinality.STREAM_UNARY,
                hermes_pb2.ChannelRequest,
                hermes_pb2.ChannelResponse,
            ),
        }


class HermesStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Handshake = grpclib.client.UnaryUnaryMethod(
            channel,
            "/hermes.Hermes/Handshake",
            hermes_pb2.Unit,
            hermes_pb2.Unit,
        )
        self.FetchCollection = grpclib.client.StreamStreamMethod(
            channel,
            "/hermes.Hermes/FetchCollection",
            hermes_pb2.CollectionRequest,
            hermes_pb2.CollectionResponse,
        )
        self.SendToChannel = grpclib.client.StreamUnaryMethod(
            channel,
            "/hermes.Hermes/SendToChannel",
            hermes_pb2.ChannelRequest,
            hermes_pb2.ChannelResponse,
        )
